name: flint
description: Analyzer lints used internally in Forus Labs' Dart & Flutter projects.
version: 2.12.0
homepage: https://github.com/forus-labs/cauldron
repository: https://github.com/forus-labs/cauldron
topics: [lints]

environment:
  sdk: '>=3.7.0 <4.0.0'
resolution: workspace

dev_dependencies:
  html: ^0.15.0
  http: ^1.0.0
  yaml: ^3.1.0
