name: flint
description: Analyzer lints used internally in Forus Labs' Dart & Flutter projects.
version: 2.7.0
homepage: https://github.com/forus-labs/cauldron
repository: https://github.com/forus-labs/cauldron

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  html: ^0.15.0
  http: ^0.13.3
  yaml: ^3.1.0
