name: flint_example
description: Example for Flint
private: true
version: 1.0.0
homepage: https://github.com/forus-labs/cauldron
repository: https://github.com/forus-labs/cauldron

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flint: ^2.1.0