name: nitrogen
description: Type safe Flutter asset generation.
topics: [assets, generation]

version: 0.4.0
homepage: https://github.com/forus-labs/cauldron/tree/master/nitrogen
repository: https://github.com/forus-labs/cauldron/

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=3.27.0"
resolution: workspace

dependencies:
  build: ^2.4.1
  build_runner: ^2.4.6
  code_builder: ^4.10.0
  dart_style: ^3.0.0
  flutter:
    sdk: flutter
  glob: ^2.1.2
  meta: ^1.9.1
  nitrogen_types:
  path: ^1.9.0
  pub_semver: ^2.1.5
  sugar:
  yaml: ^3.1.2

dev_dependencies:
  build_test: ^2.2.2
  flint:
  test: ^1.25.2
