name: sugar
description: Forus Labs' standard library extension. Utilities for date-times, timezones, collections, monads & more.
topics: [datetime, timezone, utilities]

version: 4.0.0
homepage: https://github.com/forus-labs/cauldron
repository: https://github.com/forus-labs/cauldron
issue_tracker: https://github.com/forus-labs/cauldron/issues
documentation: https://pub.dev/documentation/sugar/latest/

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  ffi: ^2.0.1
  meta: ^1.11.0
  web: ^1.1.0

dev_dependencies:
  coverage: ^1.6.3
  flint: ^2.9.0
  http: ^1.0.0
  import_sorter: ^4.6.0
  path: ^1.8.3
  test: ^1.25.0
  timezone: ^0.10.0

import_sorter:
  comments: false
